server:
  servlet:
    context-path: /api
  port: 8081

spring:
  profiles:
    active: dev

  application:
    name: user-service
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
        generate_statistics: true
        default_schema: user-service

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    operations-sorter: methods
    tags-sorter: alpha
    display-request-duration: true
    default-model-expand-depth: 10
    display-operation-id: true

logging:
  level:
    org.springframework.security: DEBUG


jwt:
  secret: my-super-secret-key-which-should-be-very-long
  issuer: NLS-Backend
  duration: 3600000

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true

---

spring:
  config:
    activate:
      on-profile: dev

  datasource:
    url: jdbc:postgresql://localhost:5432/hotel-booking
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        default_schema: user-service

