server:
  servlet:
    context-path: /api
  port: 8081

spring:
  profiles:
    active: dev

  application:
    name: user-service
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
        generate_statistics: true
        default_schema: user-service

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    operations-sorter: methods
    tags-sorter: alpha
    display-request-duration: true
    default-model-expand-depth: 10
    display-operation-id: true

logging:
  level:
    org.springframework.security: DEBUG


jwt:
  secret-key: e12ddd7c24485873318bcdfce6696932504b8cf91b42256570a03825a5c4083023ddf4f73f0c21da9ff63a4804d98b4d681c3bca88b028f6be75254078a0346530d105c2d8318b044f2c3f633ab802d18f5964ec3b063f66f01d2a0178605c2cd8267a5589432ad6f6b45b83b211eb3f57f71b32f9aa9d75e3f72b64c367703017acbe0a08caf43dbabd0a797dc79a9b97089653fc9379c59f03c69bbdde659377f6b35f4b194b26fe1b8e1b69f3dd671574168307f90b34f7a9c187762042ca47a0bc2251241b1919600fb288ecaef6bb20f935fc12a9509caefbda071bf0c03da0cae31e27e46668d60f7652a807a974c31aae72cfc0296e4f3542f8a69663
  issuer: NLS-Backend
  duration: 3600000

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true

---

spring:
  config:
    activate:
      on-profile: dev

  datasource:
    url: jdbc:postgresql://localhost:5432/hotel-booking
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        default_schema: user-service

openapi:
  server-url: http://localhost:8080/user-service/api
