server:
  servlet:
    context-path: /api
  port: 8084

spring:
  profiles:
    active: dev

  application:
    name: notification-service
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
        generate_statistics: true

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    operations-sorter: methods
    tags-sorter: alpha
    display-request-duration: true
    default-model-expand-depth: 10
    display-operation-id: true

mailjet:
  email: nls.hotel.booking@gmail.com
  name: NonLaService Hotel

---
spring:
  config:
    activate:
      on-profile: dev

  datasource:
    url: jdbc:postgresql://localhost:5432/hotel-booking
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        default_schema: notification-service

  # Mailjet Configuration
  mail:
    host: in-v3.mailjet.com
    port: 587
    username: d03b54669cfdc86e588d61b12c23f090
    password: 0c54d42e5becc1575bc99d3bd97fe612
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          ssl:
            trust: in-v3.mailjet.com

  rabbitmq:
    host: localhost
    port: 5672
    username: user
    password: password

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true

openapi:
  server-url: http://localhost:8080/notification-service/api


---
spring:
  config:
    activate:
      on-profile: stag

  datasource:
    url: jdbc:postgresql://postgres:5432/hotel-booking
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        default_schema: notification-service

  # Mailjet Configuration
  mail:
    host: in-v3.mailjet.com
    port: 587
    username: d03b54669cfdc86e588d61b12c23f090
    password: 0c54d42e5becc1575bc99d3bd97fe612
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          ssl:
            trust: in-v3.mailjet.com

  rabbitmq:
    host: rabbitmq
    port: 5672
    username: user
    password: password

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka-server:8761/eureka/
  instance:
    prefer-ip-address: true

openapi:
  server-url: http://localhost:8080/notification-service/api
