server:
  port: 8080

spring:
  profiles:
    active: dev
  main:
    web-application-type: reactive
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/user-service/**
        - id: booking-service
          uri: lb://booking-service
          predicates:
            - Path=/booking-service/**
        - id: notification-service
          uri: lb://notification-service
          predicates:
            - Path=/notification-service/**
        - id: payment-service
          uri: lb://payment-service
          predicates:
            - Path=/payment-service/**
        - id: recommendation-service
          uri: lb://recommendation-service
          predicates:
            - Path=/recommendation-service/**


logging:
  level:
    org.springframework.security: DEBUG

springdoc:
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
    config-url: /v3/api-docs/swagger-config
    urls:
      - name: api-gateway
        url: /v3/api-docs
      - name: user-service
        url: /user-service/api/v3/api-docs
      - name: booking-service
        url: /booking-service/api/v3/api-docs
      - name: payment-service
        url: /payment-service/api/v3/api-docs
      - name: notification-service
        url: /notification-service/api/v3/api-docs
      - name: recommendation-service
        url: /recommendation-service/api/v3/api-docs

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true

---

spring:
  config:
    activate:
      on-profile: dev

  datasource:
    url: jdbc:postgresql://localhost:5432/hotel-booking
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        default_schema: api-gateway

jwt:
  secret-key: e12ddd7c24485873318bcdfce6696932504b8cf91b42256570a03825a5c4083023ddf4f73f0c21da9ff63a4804d98b4d681c3bca88b028f6be75254078a0346530d105c2d8318b044f2c3f633ab802d18f5964ec3b063f66f01d2a0178605c2cd8267a5589432ad6f6b45b83b211eb3f57f71b32f9aa9d75e3f72b64c367703017acbe0a08caf43dbabd0a797dc79a9b97089653fc9379c59f03c69bbdde659377f6b35f4b194b26fe1b8e1b69f3dd671574168307f90b34f7a9c187762042ca47a0bc2251241b1919600fb288ecaef6bb20f935fc12a9509caefbda071bf0c03da0cae31e27e46668d60f7652a807a974c31aae72cfc0296e4f3542f8a69663
