server:
  port: 8080

spring:
  profiles:
    active: dev

  main:
    web-application-type: reactive

  application:
    name: api-gateway

  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/user-service/**
#        - id: user-service-swagger-docs
#          uri: lb://user-service
#          predicates:
#            - Path=/user-service/v3/api-docs
#          filters:
#            - RewritePath=/user-service/v3/api-docs, /api/v3/api-docs

security:
  basic:
    enabled: false

logging:
  level:
    org.springframework.security: DEBUG

swagger:
  services:
    - name: user-service
      url: http://localhost:8081/api/v3/api-docs
    - name: booking-service
      url: http://localhost:8082/api/v3/api-docs
    - name: payment-service
      url: http://localhost:8083/v3/api-docs


springdoc:
  api-docs:
    enabled: true
    path: /v3/api-docs
  swagger-ui:
    enabled: true
    url: /api-docs/aggregate
    disable-swagger-default-url: true
    urls:
      - name: api-gateway
        url: /v3/api-doc
      - name: user-service
        url: http://localhost:8081/api/v3/api-docs
      - name: booking-service
        url: http://localhost:8082/api/v3/api-docs

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true

---

spring:
  config:
    activate:
      on-profile: dev

  datasource:
    url: jdbc:postgresql://localhost:5432/hotel-booking
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        default_schema: api-gateway


